app: demoSls
service: demoSls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  firstFunction:
    handler: src/test.handler
    events:
      - httpApi:
          path: /users
          method: get
  createUser:
    handler: src/createUser.handler
    events:
      - httpApi:
          path: /users
          method: post
  findUserByName:
   handler: src/findUsers.handler
   events:
     - httpApi: 
          path: /users/{name}
          method: get
plugins:
  - serverless-offline
  - serverless-plugin-typescript
